# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Half Actor
email: jutkko (at) gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This section is kinda important, I will come to this later.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jutkko.github.io" # the base hostname & protocol for your site
twitter_username: jutkko
github_username:  jutkko

# Build settings
markdown: kramdown
